### ISSUE TITLE
'Copy link' button as a sharing option

### ISSUE THREAD

**Issue by dan-burnage** [onespacemedia/osm-jet#10]
It would be good to have a button as part of the sharing options that copies the link URL allowing people to share the page in other places that aren't Facebook, Twitter or Linkedin

![Screenshot 2019-08-05 at 16 55 08](https://user-images.githubusercontent.com/50490246/62477889-cab52e80-b7a1-11e9-8cf5-76fa43c0b5b4.png)

**Comment by AidanCurrah** [comment]
Added in 1333ab4
