### ISSUE TITLE
Page save issues

### ISSUE THREAD

**Issue by joe-hastings** [onespacemedia/osm-jet#11]
Seen on Tees, pages aren't always saving, sometimes you get kicked back out to the add page screen spotted by Charley.

Steps to recreate:
- Open the admin
- Go to pages
- Search for a page (any page)
- Click add page
- Select content
- Fill in the title, CTA and uncheck the add to navigation button
- Click save and return (or any save variation)
- Taken back to the page type page

**Comment by joe-hastings** [comment]
Note that it is an intermittent bug

**Comment by AidanCurrah** [comment]
It feels like this is a bizarre issue where is you have `_changelist_filters=%3D` then the `Save and return` or other option just don't even try to save the page

**Comment by lewiscollard** [comment]
Actually a `cms` bug, fixed in https://github.com/onespacemedia/cms/commit/9168ab96c20b939be9bfc9ea695a8a940acb5f8b
