### ISSUE TITLE
Compact inline - bug when there's a form error while saving

### ISSUE THREAD

**Issue by daniel-clayton** [onespacemedia/osm-jet#31]
If you add a content section but miss out a required field, for instance, then an additional content section appears in the form and all of the 'remove' buttons are missing so you can't get rid of them.

![image](https://user-images.githubusercontent.com/28294212/65586207-aee93000-df7b-11e9-861a-6835749f7b7a.png)

**Comment by AidanCurrah** [comment]
It seems that the default Jet JS for `CompactInline`s takes the hidden form into account when updating the management form's `TOTAL_FORMS` value. This can be either patched in our `compact-inline.js` helper via an on-save function to properly count the forms or we can patch it directly once we port over the JS to our own local version.
