### ISSUE TITLE
Backspacing does not work on media gallery titles

### ISSUE THREAD

**Issue by lewiscollard** [onespacemedia/osm-jet#32]
As reported by @charley-rose in a private repo:

> Whilst editing files already uploaded to the media gallery, the backspace doesn't work so you can't delete titles unless you highlight the whole text then start typing. Seems to only be affecting the backspace.

It seems this has been around since at least 1.0.4. It feels like something is hooking the input/keypress/keydown event here.

**Comment by AidanCurrah** [comment]
Fixed by https://github.com/onespacemedia/cms/commit/e095bc5eb4681917dba68772bb6e85b9f786eea2
