### ISSUE TITLE
Custom sidebar doesn't play nice with permissions

### ISSUE THREAD

**Issue by AidanCurrah** [onespacemedia/osm-jet#34]
If you specify a custom user sidebar using `JET_SIDE_MENU_ITEMS`, it'll always try to display those items regardless of wether the user has the permissions to edit those objects of not which causes the site to throw a 500 error.

**Comment by lewiscollard** [comment]
Throwing a 500 isn't what I got on my last upgrade - I had the menu items attempting to display, but displaying with an empty link and link text. That is still suboptimal!

**Comment by lewiscollard** [comment]
It also occurred to me: this is actually throwing a 403, but on our projects using Jinja2 the standard 403.html throws an exception because it's attempting to parse the Django-syntax `403.html` as Jinja2, which throws the 500.

**Comment by AidanCurrah** [comment]
Fixed in 16175d9
