### ISSUE TITLE
Items in many-to-many widget run into the boundaries of the containing element

### ISSUE THREAD

**Issue by lewiscollard** [onespacemedia/osm-jet#36]
Sample from a typical news app:

![Screenshot 2019-10-22 at 16 43 56](https://user-images.githubusercontent.com/4973097/67304221-6aee3a00-f4eb-11e9-8b9c-5097f9e75059.png)

See that "In the News" has a margin distancing itself from the top border of its containing element, but none on the bottom (it sits flush with the border).

**Comment by AidanCurrah** [comment]
FIxed in b68b163
