### ISSUE TITLE
Sorted M2M, add the ability to edit an item

### ISSUE THREAD

**Issue by joe-hastings** [onespacemedia/osm-jet#39]
To edit this sidebox for example, you just have to go to components, sidebox and remember the name of the one you want to edit which is a bit of a pain. Maybe we could add an edit pencil in each row?

![Screenshot 2019-10-30 at 16 33 15](https://user-images.githubusercontent.com/11661855/67878392-2722b280-fb33-11e9-88d2-a3e278f77a3e.png)

**Comment by AidanCurrah** [comment]
Added in cbf50e
