### ISSUE TITLE
Adding new object from many to many has no sidebar

### ISSUE THREAD

**Issue by joe-hastings** [onespacemedia/osm-jet#6]
![Screenshot 2019-07-11 at 10 22 42](https://user-images.githubusercontent.com/11661855/61038962-d7727c80-a3c5-11e9-8382-338cbce75c48.png)

**Comment by lewiscollard** [comment]
This should be fixed in this one, right? https://github.com/onespacemedia/cms/commit/7f05c6e0189989e17ada3aed2b32256fa112307f

**Comment by AidanCurrah** [comment]
That comment was put on the wrong issue. The problem here is that a tab is being opened when it should be opened in the Jet slid-in iframe

**Comment by daniel-clayton** [comment]
Fixed in latest release
