### ISSUE TITLE
Ticks in tables are white and not visible

### ISSUE THREAD

**Issue by joe-hastings** [onespacemedia/osm-jet#8]
Currently a problem on Geospock so need to ensure it gets updated there once it's fixed:

![Screenshot 2019-07-30 at 11 30 50](https://user-images.githubusercontent.com/11661855/62122453-9df2aa00-b2bd-11e9-97a1-97f0727f6b7f.png)

**Comment by AidanCurrah** [comment]
Fixed in 727544e
